[build]
command = "npm run build"
publish = "build"

[build.environment]
REACT_APP_API_KEY = "your_api_key" # Example environment variable

[build.lifecycle]
onPreBuild = "npm install -g yarn"
onBuild = "yarn install"
